version: "3"

services:
  phoenix:
    build: .
    volumes:
      - ./app:/app
    ports:
      - "4000:4000"
    depends_on:
      - db
  db:
    image: postgres:12.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /postgresql/d/pgdata
    restart: always
    volumes:
      - ./pgdata:/postgresql/data
